dev_addr: 77.73.70.153:8000
site_name: Nr1 (wuseman's wiki)
site_author: wuseman
site_description: >-
  The personal website of wuseman, it's the Nr1 wiki for cool tips and trikes for all kind of hacks/cracks you can imagine
copyright: |
  Copyright &copy; 2015 - 2022 <a href="https://github.com/wuseman"  target="_blank" rel="noopener">wuseman</a>
site_url: https://www.nr1.nu
repo_name: ""
repo_url: "https://github.com/wuseman/www.nr1.nu"
docs_dir: docs/
site_dir: site
edit_uri: docs/src/markdown

extra:
  analytics:
    provider: google
    property: G-B5KK88V0K4


extra_css:
  - assets/pymdownx-extras/katex.min.css
  - assets/pymdownx-extras/extra-e384f43f0f.css

extra_javascript:
  - assets/pymdownx-extras/katex.min.js
  - assets/pymdownx-extras/polyfill.min.js
  - assets/pymdownx-extras/tex-mml-chtml.js
  - assets/pymdownx-extras/extra-loader-5bb526e4.js
  - assets/pymdownx-extras/m.js


# Configuration
theme:
  name: material
  custom_dir: !ENV [THEME_DIR, "material"]
  static_templates:
    - 404.html
  include_search_page: false
  search_index_only: true
  language: en
  features:
     - content.code.annotate
     - content.tabs.link
     - content.tooltips
    # - header.autohide
    # - navigation.expand
     - navigation.indexes
     - navigation.instant
    # - navigation.prune
    # - navigation.sections
     - navigation.tabs
     - navigation.tabs.sticky
     - navigation.top
     - navigation.tracking
     - search.highlight
     - search.share
     - search.suggest
#     - toc.follow
#     - toc.integrate
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - bash
    - console
    - shell
    - python
    - perl
    - tcl 
    - powershell
    - ardunio
    - php
    - json
    - kotlin
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
  palette:
    - scheme: dracula
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: default
      primary: black       # Top Bar
      accent: deep purple              # SWelector
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
# https://smarie.github.io/mkdocs-gallery/
  - search:
      lang: en
      lang: sv
      min_search_length: 3
      indexing: 'full'
#  - pdf-export
  - rss:
      abstract_chars_count: 160  # -1 for full content
      categories:
        - tags
      comments_path: "#__comments"
      date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%Y-%m-%d %H:%M"
      enabled: true
      feed_ttl: 1440
      image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
      length: 20
      pretty_print: false
      match_path: ".*"
      url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
  - git-revision-date:
      enabled_if_env: CI
  - minify:
      minify_html: true



# Customization
extra:
  version: 1.0
  analytics:
    provider: google
    property: G-B5KK88V0K4
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wuseman
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/wuseman1

extra_css:
  - assets/stylesheets/wuseman/katex.min.css ### For right menu in wikis
  - assets/stylesheets/wuseman/extra-e384f43f0f.css ### For Dracula

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - smarty:
  - toc:
      permalink: True
      separator: "_"
      baselevel: 5
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: ""
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        # Mermaid diagrams
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format {kwds: {mode: generic, tag: pre}}
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/object/apply:pymdownx.arithmatex.arithmatex_inline_format {kwds: {mode: generic}}
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: wuseman
      repo: www.nr1.nu
      normalize_issue_symbols: true
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
#  - pymdownx.emoji:
#      emoji_index: !!python/name:materialx.emoji.twemoji
#      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
      generic: true
      block_tag: 'pre'
  - pymdownx.mark:
  - pymdownx.striphtml:
  - pymdownx.snippets:
      base_path:
      - docs/about
      auto_append:
      - index.md
      check_paths: true
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.saneheaders:
