dev_addr: 77.73.70.153:8000
site_name: Nr1 (wuseman's wiki)
site_author: wuseman
site_description: >-
  The personal website of wuseman, it's the Nr1 wiki for cool tips and trikes for all kind of hacks/cracks you can imagine
copyright: |
  Copyright &copy; 2015 - 2022 <a href="https://github.com/wuseman"  target="_blank" rel="noopener">wuseman</a>
site_url: https://www.nr1.nu
repo_name: ""
repo_url: "https://github.com/wuseman/www.nr1.nu"
docs_dir: docs/src/markdown
site_dir: site
edit_uri: tree/master/docs/src/markdown

extra:
  analytics:
    provider: google
    property: G-B5KK88V0K4

extra_css:
  - assets/pymdownx-extras/katex.min.css
  - assets/pymdownx-extras/extra-e384f43f0f.css

extra_javascript:
  - assets/pymdownx-extras/katex.min.js
  - assets/pymdownx-extras/polyfill.min.js
  - assets/pymdownx-extras/tex-mml-chtml.js
  - assets/pymdownx-extras/extra-loader-5bb526e4.js

theme:
  nav_style: dark
  use_directory_urls: true
  name: material
  favicon: images/favicon.png
  custom_dir: docs/theme
  static_templates:
    - 404/404.html
  icon:
    logo: material/book-open-page-variant

  palette:
    scheme: dracula
    primary: deep purple
    accent: deep purple

  features:
    - navigation.tabs
    - navigation.top
#    - navigation.indexes
    - content.tabs.link
    - navigation.prune
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - bash
    - console
    - shell
    - python
    - perl
    - tcl 
    - powershell
    - ardunio
    - php
    - json
    - kotlin
markdown_extensions:
  - smarty:
  - toc:
      permalink: True
      separator: "_"
      baselevel: 5
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: ""
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        # Mermaid diagrams
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format {kwds: {mode: generic, tag: pre}}
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/object/apply:pymdownx.arithmatex.arithmatex_inline_format {kwds: {mode: generic}}
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: facelessuser
      repo: www.nr1.nu
      normalize_issue_symbols: true
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
#  - pymdownx.emoji:
#      emoji_index: !!python/name:materialx.emoji.twemoji
#      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
      generic: true
      block_tag: 'pre'
  - pymdownx.mark:
  - pymdownx.striphtml:
  - pymdownx.snippets:
      base_path:
      - docs/src/markdown/.snippets
      auto_append:
      - refs.md
      check_paths: true
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.saneheaders:

plugins:
# https://smarie.github.io/mkdocs-gallery/
  - search:
      lang: en
      lang: sv
      min_search_length: 3
      indexing: 'full'
#  - pdf-export
  - rss:
      abstract_chars_count: 160  # -1 for full content
      categories:
        - tags
      comments_path: "#__comments"
      date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%Y-%m-%d %H:%M"
      enabled: true
      feed_ttl: 1440
      image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
      length: 20
      pretty_print: false
      match_path: ".*"
      url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
  - git-revision-date:
      enabled_if_env: CI
  - minify:
      minify_html: true

extra:
  analytics:
    provider: matomo
    url: www.nr1.nu/matomo
    site: 1
  analytics: 
    provider: google
    property: G-B5KK88V0K4
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target=_blank>feedback form</a>.
  
  version: 1.0

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wuseman
    - icon: fontawesome/brands/discord
      link: https://discord.gg/wuseman
nav: 
  - Home:
    - About: about/index.md
    - Contact: about/contact.md
    - CV: about/cv.md
    - Help: about/usage_notes.md
  - Cracking: 
        -  cracking/index.md
        - 'wloader': cracking/wloader/README.md
  - Gentoo:
     - gentoo-cheatsheet: gentoo/gentoo-tools.md
     - gentoo-chroot: gentoo/gentoo-chroot.md
     - gentoo-vmware: gentoo/gentoo-vmware.md
     - wuseman-overlay: gentoo/wuseman-overlay/README.md
     - gentoo-wupdate:  gentoo/gentoo-update.md
  - Hacking: 
     - 'hacking/index.md'
     - Android: 
        - WADBPWN: hacking/android/wadpwn/README.md
     - Bios: 
        - HP Bios: hacking/bios/hp_device_and_bios-hacking/README.md
     - Bruteforce: 
        - EMAGNET: 'hacking/bruteforce/emagnet/readme.md'
        - WBRUTER: hacking/bruteforce/wbruter/README.md
        - WSSH: hacking/bruteforce/wssh/README.md
     - Cameras:
        - Biltemas Babycam: hacking/cameras/biltemas_babycam/README.md
        - DLink 6100lh: hacking/cameras/dlink-6100lh/README.md
     - Chromebook: 
        - Acer C720: hacking/chromebook/acer_chromebook_c720/README.md
        - Acer C740: hacking/chromebook/acer_chromebook_c740/README.md
        - Asus C203sa: hacking/chromebook/asus_c203sa/README.md
     - Radio: 
        - Boose Soundtouch: hacking/radio/boose_soundtouch/README.md
     - Router:
        - Inteno:
            - FG500: hacking/routers/inteno/FG500/README.md
        - Technicolor: 
           - DGAGA4330TS: hacking/routers/technicolor/dga4330ts/README.md
           - TG799vacXTREAM 17.2: hacking/routers/technicolor/t799vacxtreme17.2/README.md
           - TG799vacXTREAM 18.1: hacking/routers/technicolor/tg799vacxtream18.1/README.md
           - TG799vnv2-10.5.1.Q:  https://github.com/wuseman/TG799vnv2-10.5.1.Q-SMART-3.6.1/blob/87c7c016a8d9a44cae298c16a1233348350a6de3/README.md
        - Sagemcom: 
           - F@st 5430: hacking/routers/sagemcom/FAST5370e/README.md
     - Switches:
        - Cisco: 
           - C1111 8PLTEEA: hacking/switches/cisco/c1111_8plteea/README.md
        - Édge Core: 
           - ES3510MA: hacking/switches/edge-core/es3510ma/README.md
     - Misc: 
           - UserAgents: 'misc/user_agents.md'
     - Wordlists: 
           - Swedish Wordlist: hacking/bruteforce/swedish_wordlist.txt/README.md
  - Linux:
     - 'linux/index.md'
     - apt: linux/apt.md
     - arp: linux/arp.md
     - awk: linux/awk.md
     - bash: linux/bash.md
     - bluetoothctl: linux/bluetoothctl.md
     - btmgt: linux/btmgt.md
     - btmon: linux/btmon.md
     - chroot: linux/chroot.md
     - ciptool: linux/ciptool.md
     - comm: linux/comm.md
     - cryptsetup: linux/cryptsetup.md
     - curl: linux/curl.md
     - databases: linux/databases.md
     - dd: linux/dd.md
     - dev_and_proc: linux/dev_and_proc.md
     - df: linux/df.md
     - diff: linux/diff.md
     - dig: linux/dig.md
     - dpkg: linux/dpkg.md
     - du: linux/du.md
     - echo: linux/echo.md
     - emerge: linux/emerge.md
     - enviroment: linux/enviroment.md
     - exiftool: linux/exiftool.md
     - ffmpeg: linux/ffmpeg.md
     - find: linux/find.md
     - for: linux/for.md
     - git: linux/git.md
     - gnupg: linux/gnupg.md
     - grep: linux/grep.md
     - hciconfig: linux/hciconfig.md
     - hcitool: linux/hcitool.md
     - hexdump: linux/hexdump.md
     - ip: linux/ip.md
     - iptables: linux/iptables.md
     - iw: linux/iw.md
     - kernel: linux/kernel.md
     - kill: linux/kill.md
     - lftp: linux/lftp.md
     - links: linux/links.md
     - license: linux/license.md
     - log: linux/log.md
     - ls: linux/ls.md
     - lsof: linux/lsof.md
     - lynx: linux/lynx.md
     - mail: linux/mail.md
     - man: linux/man.md
     - matomo: linux/matomo.md
     - merge-tricks: linux/merge-tricks.md
     - mkdocs: linux/mkdocs.md
     - mplayer: linux/mplayer.md
     - mutt: linux/mutt.md
     - mysql: linux/mysql.md
     - nc: linux/nc.md
     - netstat: linux/netstat.md
     - nmap2: linux/nmap2.md
     - nmap: linux/nmap.md
     - od: linux/od.md
     - parallel: linux/parallel.md
     - paste_and_pr: linux/paste_and_pr.md
     - perf: linux/perf.md
     - pgrep: linux/pgrep.md
     - ping: linux/ping.md
     - pkill: linux/pkill.md
     - printf: linux/printf.md
     - ps: linux/ps.md
     - rdesktop: linux/rdesktop.md
     - rename: linux/rename.md
     - rg: linux/rg.md
     - rm: linux/rm.md
     - rsync: linux/rsync.md
     - screen: linux/screen.md
     - sed: linux/sed.md
     - shuf: linux/shuf.md
     - shopt: linux/shopt.md
     - sort: linux/sort.md
     - sqlmap: linux/sqlmap.md
     - sqlite3: linux/sqlite3.md
     - ssh-config: linux/ssh-config.md
     - ssh-mixed: linux/ssh.md
     - sshfs: linux/sshfs.md
     - ssh-log: linux/ssh-log.md
     - stat: linux/stat.md
     - strace: linux/strace.md
     - sudo: linux/sudo.md
     - syslog-ng: linux/syslog-ng/syslog-conf.ng.md
     - sys: linux/sys.md
     - tar: linux/tar.md
     - tcpdump: linux/tcpdump.md
     - thermal: linux/thermal.md
     - top: linux/top.md
     - tshark: linux/tshark.md
     - until: linux/until.md
     - vim: linux/vim.md
     - wget: linux/wget.md
     - whatismyip: linux/whatismyip.md
     - while: linux/while.md
     - wireguard: linux/wireguard.md
     - xargs: linux/xargs.md
  - Wiki:
     - 'wiki/index.md'
     - adb:
        - 'adb-cheatsheet': wiki/adb/readme.md
        - 'at-commands': wiki/adb/at.md
        - 'uusd-codes': wiki/adb/uusd_codes.md
     - emagnet: 
        - wiki/emagnet/Getting-Started.md
        - wiki/emagnet/About.md
        - wiki/emagnet/Configurations-&-Installation.md
        - wiki/emagnet/Home.md
        - wiki/emagnet/Leaked-Databases.md
        - wiki/emagnet/Searching-&-Regex.md
        - wiki/emagnet/_Footer.md
        - wiki/emagnet/__foot.md

  - Windows:
     - bios: windows/bios.md
     - wmic: windows/wmic2.md
